# Favorite.delete_all
# ArtistFestival.delete_all
# # Organizer.delete_all
# Artist.delete_all
# Fan.delete_all
# Festival.delete_all

# #ORGANIZERS
# # organizer1 = Organizer.new(username: "Live Nation")
# # organizer2= Organizer.new(Username: "Insomniac")
# # organizer3 = Organizer.new(username: "SFX entertainment")
# # organizer4 = Organizer.new(username: "AEG")


# #ARTISTS

gaga = Artist.create(name: "Lady Gaga", genre:"Pop", artist_image: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Lady_Gaga_Grammys_2017.png", bio: "Stefani Joanne Angelina Germanotta  (born March 28, 1986), known professionally as Lady Gaga, is an American singer, songwriter, record producer, actress, and businesswoman. She is known for reinventing herself throughout her career and for her versatility in numerous areas of the entertainment industry.", video:"https://www.youtube.com/embed/bo_efYhYU2A")
artist1 = Artist.create(name: "Pearl Jam", genre:"Rock", artist_image: "https://upload.wikimedia.org/wikipedia/commons/5/5b/EddieVedder.jpg", bio: "Pearl Jam is an American rock band formed in 1990 in Seattle, Washington. The band's lineup consists of founding members Jeff Ament (bass guitar), Stone Gossard (rhythm guitar), Mike McCready (lead guitar), and Eddie Vedder (lead vocals, guitar), as well as Matt Cameron (drums), who joined in 1998. Keyboardist Boom Gaspar has also been a touring/session member with the band since 2002. Drummers Jack Irons, Dave Krusen, Matt Chamberlain, and Dave Abbruzzese are former members of the band.", video: "https://www.youtube.com/embed/MS91knuzoOA")
artist2 = Artist.create(name: "Billie Eilish", genre:"Electropop", artist_image:"https://upload.wikimedia.org/wikipedia/en/a/af/Billie_Eilish_at_Pukkelpop_%2848590443381%29_%28cropped%29_square.jpg", bio: "Billie Eilish Pirate Baird O'Connell (born December 18, 2001) is an American singer and songwriter. She first gained attention in 2015 when she uploaded the song 'Ocean Eyes' to SoundCloud, which was subsequently released by the Interscope Records subsidiary Darkroom. The song was written and produced by her brother Finneas, with whom she collaborates on music and live shows. Her debut EP, Don't Smile at Me (2017), became a sleeper hit, reaching the top 15 in the US, UK, Canada, and Australia.", video: "https://www.youtube.com/embed/DyDfgMOUjCI")
artist3 = Artist.create(name: "Madonna", genre:"Pop", artist_image: "https://pagesix.com/wp-content/uploads/sites/3/2020/01/madonna-03.jpg?quality=90&strip=all&w=618&h=410&crop=1", bio: "Madonna Louise Ciccone ( born August 16, 1958) is an American singer-songwriter, actress, author, and record executive. Having been referred to as the 'Queen of Pop' since the 1980s, she is regarded as one of the most impactful figures in popular culture. Madonna is noted for her continual reinvention and versatility in music production, songwriting, and visual presentation. She has pushed the boundaries of artistic expression in mainstream music, while remaining completely in charge of every aspect of her career. Her works, which incorporate social, political, sexual, and religious themes, have generated both critical acclaim and controversy. Madonna is often cited as an influence by other artists.", video: "https://www.youtube.com/embed/xAxNaLAR2to")
gorillas = Artist.create(name: "Gorillaz", genre:"Alternative rock", artist_image: "https://upload.wikimedia.org/wikipedia/en/f/fc/Gorillaz_Song_Machine_Promo_Art.jpg", bio: "Gorillaz are a British virtual band created in 1998 by musician Damon Albarn and artist Jamie Hewlett. The band primarily consists of four animated members: Stuart '2-D' Pot, Murdoc Niccals, Noodle, and Russel Hobbs. Their fictional universe is presented in music videos, interviews and short cartoons. In reality, Albarn is the only permanent musical contributor, and Gorillaz' music often features collaborations with a wide range of featured artists. Remi Kabaka Jr. became producer for the band in 2016 after several years providing the voice of Russel Hobbs and was listed as an official member alongside Albarn and Hewlett in the 2019 documentary Gorillaz: Reject False Icons.", video: "https://www.youtube.com/embed/1V_xRb0x9aw")
taylor = Artist.create(name: "Taylor Swift", genre: "Pop", artist_image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/191125_Taylor_Swift_at_the_2019_American_Music_Awards_%28cropped%29.png/220px-191125_Taylor_Swift_at_the_2019_American_Music_Awards_%28cropped%29.png", bio: "Taylor Alison Swift (born December 13, 1989) is an American singer-songwriter. Her narrative songwriting, which often centers around her personal life, has received widespread media coverage. Born in West Reading, Pennsylvania, Swift relocated to Nashville, Tennessee in 2004 to pursue a career in country music. At age 14, she became the youngest artist signed by the Sony/ATV Music publishing house, and at age 15, she signed her first record deal. Her 2006 eponymous debut studio album was the longest-charting album of the 2000s on the Billboard 200. Its third single, Our Song, made her the youngest person to single-handedly write and perform a number-one song on the Billboard Country Airplay chart. Swifts breakthrough second studio album, Fearless (2008), won four Grammy Awards, including Album of the Year, and was certified Diamond by the Recording Industry Association of America. It yielded the crossover hit singles Love Story and You Belong with Me.", video: "https://www.youtube.com/embed/e-ORhEE9VVg")
drake  = Artist.create(name: "Drake", genre: "Hip hop", artist_image: "https://www.rollingstone.com/wp-content/uploads/2019/10/Drake.jpg?resize=1800,1200&w=1200”, bio: 'Aubrey Drake Graham (born October 24, 1986) is a Canadian rapper, singer, songwriter, record producer, actor, and entrepreneur. A prominent figure in popular music, Drake is widely credited for popularizing the Toronto sound to the music industry. He first gained recognition as an actor on the teen drama television series Degrassi: The Next Generation (2001-2007); intent on pursuing a career in music, he left the series in 2007 after releasing his debut mixtape Room for Improvement. He released two further independent projects, Comeback Season and So Far Gone, before signing to Young Money Entertainment in June 2009.", video: "https://www.youtube.com/embed/JFm7YDVlqnI")
Khalid  = Artist.create(name: "DJ Khaled", genre: "Hip Hop",artist_image: "https://upload.wikimedia.org/wikipedia/commons/a/af/DJ_Khaled_2012.jpg", bio: "Khaled Mohamed Khaled (born November 26, 1975), better known by his stage name DJ Khaled, is an American DJ, record executive, record producer, author, and media personality. Khaled first gained prominence as a radio host in the 1990s on the radio station 99 Jamz, and translated his popularity by working with Terror Squad as a DJ for their live performances. After gaining production credits on the group's material,[4] Khaled released his debut studio album Listennn... the Album in 2006, which earned gold certification. He followed it with the album We the Best (2007), which contained the top 20 single Im So Hood. His subsequent two releases — We Global (2008) and Victory (2010) — were released after he founded the record label We the Best Music Group. Both albums charted in the top ten on the US Billboard 200, with the latter containing the single All I Do Is Win, which was eventually certified triple platinum.", video: "https://www.youtube.com/embed/-iNWEwLfkv8")
ariana  = Artist.create(name: "Ariana Grande", genre: "R&B", artist_image: "https://media.vanityfair.com/photos/586413ae12f608c91db97830/master/w_2560%2Cc_limit/ariana-grande-best-year-2016.jpg", bio: "Ariana Grande-Butera (born June 26, 1993) is an American singer, songwriter, and actress. Born in Boca Raton, Florida, Grande began her career in the 2008 Broadway musical 13. She rose to prominence for her role as Cat Valentine in the Nickelodeon television series Victorious (2010–2013) and Sam & Cat (2013–2014). She subsequently signed with Republic Records in 2011 after the labels executives discovered YouTube videos of her covering songs. Her 1950s doo-wop-influenced pop and R&B debut album, Yours Truly (2013), topped the US Billboard 200 chart, while its lead single, The Way, charted in the top ten of the US Billboard Hot 100.", video: "https://www.youtube.com/embed/QYh6mYIJG2Y")
beyonce  = Artist.create(name: "Beyoncé", genre: "R&B", artist_image: "https://upload.wikimedia.org/wikipedia/commons/1/17/Beyonc%C3%A9_at_The_Lion_King_European_Premiere_2019.png", bio: "Bio Beyoncé Giselle Knowles-Carter ( born September 4, 1981) is an American singer, songwriter, record producer, dancer, actress and filmmaker. Born and raised in Houston, Texas, Beyoncé performed in various singing and dancing competitions as a child. She rose to fame in the late 1990s as the lead singer of Destiny's Child, one of the best-selling girl groups of all time. During Destiny's Child's hiatus, Beyoncé made her theatrical film debut with a role in the US box-office number-one Austin Powers in Goldmember (2002) and began her solo music career. She became the first music act to debut at number one with their first six solo studio albums on the Billboard 200", video: "https://www.youtube.com/embed/bnVUHWCynig")
modest  = Artist.create(name: "Modest Mouse", genre: "Indie Rock", artist_image: "https://www.nme.com/wp-content/uploads/2019/03/GettyImages-1055015804-696x442.jpg", bio: "Modest Mouse is an American rock band formed in 1992 in Issaquah, Washington and currently based in Portland, Oregon. The founding members are lead singer/guitarist Isaac Brock, drummer Jeremiah Green, and bassist Eric Judy. Strongly influenced by Pavement, Pixies, XTC, and Talking Heads, the band rehearsed, rearranged, and recorded demos for almost two years before finally signing with small-town indie label K Records and releasing numerous singles. Since their 1996 debut This Is a Long Drive for Someone with Nothing to Think About, the bands lineup has centered on Brock and Green. The band achieved mainstream success with their fourth album Good News for People Who Love Bad News (2004) and its singles Float On and Ocean Breathes Salty. Judy performed on every Modest Mouse album until his departure in 2012. Guitarist Johnny Marr (formerly of the Smiths) joined the band in 2006, shortly following percussionist Joe Plummer (formerly of the Black Heart Procession) and multi-instrumentalist Tom Peloso, to work on the album We Were Dead Before the Ship Even Sank (2007). Guitarist Jim Fairchild joined the band in 2009. The bands sixth album Strangers to Ourselves was released on March 17, 2015.", video: "https://www.youtube.com/embed/CTAud5O7Qqk")
tiesto  = Artist.create(name: "Tiësto", genre: "Dance pop", artist_image: "https://upload.wikimedia.org/wikipedia/commons/6/68/Ti%C3%ABsto_%40_Airbeat_One_2017.jpg", bio: "Tijs Michiel Verwest OON (Dutch pronunciation:born 17 January 1969), better known by his stage name Tiësto, is a Dutch DJ and record producer from Breda, North Brabant. He was named the Greatest DJ of All Time by Mix magazine in a poll voted by the fans.In 2013, he was voted by DJ Mag readers as the best DJ of the last 20 years. He is also regarded as the Godfather of EDM by many sources.In 1997, he founded the label Black Hole Recordings with Arny Bink, where he released the Magik and In Search of Sunrise CD series. Tiësto met producer Dennis Waakop Reijers in 1998; the two have worked together extensively since then.", video: "https://www.youtube.com/embed/Gj0v9IRvujs")
infected  = Artist.create(name: "Infected Mushroom", genre: "Psychedelic trance", artist_image: "https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9/p960x960/95023821_10157489970702261_6564917224866316288_o.jpg?_nc_cat=107&_nc_sid=85a577&_nc_ohc=Ubok0iL0hB0AX80vZ2e&_nc_ht=scontent-sea1-1.xx&_nc_tp=6&oh=b35b07d00df107f46efd569ccbc9b7ef&oe=5F62A5D7", bio: "Infected Mushroom is an Israeli musical duo formed in Haifa in 1996 by producers Erez Eisen and Amit Duvdevani. They produce and perform psytrance, electronica, dream trance and psychedelic music. They are one of the best-selling groups in Israeli music history in terms of both domestic and international sales.They employ a variety of musical sources, including acoustic guitars and complex synthesized basses. Their compositions often contain changes of drum beat and tempo. Infected Mushrooms live shows feature vocals and analogue instruments in performances that are set against a multimedia backdrop.", video: "https://www.youtube.com/embed/Z6hL6fkJ1_k")
guetta = Artist.create(name:"David Guetta", genre:"Electronic dance music, House music, Progressive house, Electro house, Dance-pop, Big room house, Future house", artist_image:"https://upload.wikimedia.org/wikipedia/commons/4/4b/David_Guetta_live_%40_MTV_EMA_2018.png", bio: "Pierre David Guetta (French pronunciation: born 7 November 1967) is a French DJ, record producer and songwriter. He has sold over nine million albums and thirty million singles worldwide. In 2011, Guetta was voted as the number one DJ in the DJ Mag Top 100 DJs poll. In 2013, Billboard crowned \"When Love Takes Over\" as the number one dance-pop collaboration of all time. Born and raised in Paris, he released his first album, Just a Little More Love, in 2002. Later, he released Guetta Blaster (2004) and Pop Life (2007). Guetta achieved mainstream success with his 2009 album One Love, which included the hit singles \"When Love Takes Over,\" \"Gettin' Over You,\" \"Sexy Bitch\", and \"Memories,\" the first three of which reached number one in the United Kingdom. The 2011 follow-up album, Nothing but the Beat, continued this success, containing the hit singles \"Where Them Girls At\", \"Little Bad Girl\", \"Without You\", \"Titanium\" and \"Turn Me On.\" He has been called the \"grandfather of EDM.", video:"https://www.youtube.com/embed/JRfuAukYTKg")
alanis = Artist.create(name:"Alanis Morissette", genre:"Alternative rock, Rock, Grunge", artist_image: "https://upload.wikimedia.org/wikipedia/commons/8/82/Alanis_Morissette_5-19-2014.jpg", bio:"", video:"https://www.youtube.com/embed/Jne9t8sHpUc")

# #FANS
# fan1 = Fan.create(name:"Ronak")
# fan2 = Fan.create(name:"Daniel")
# fan2 = Fan.create(name:"Noa")
# fan2 = Fan.create(name:"Brad")

#FESTIVALS
festival1 = Festival.create(name: "Sasquatch", location: "Washington", organizer_id: 1, image_url: "https://upload.wikimedia.org/wikipedia/commons/4/48/Gorge_Amphitheatre.jpg", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"Sasquatch! Music Festival was an annual music festival held at The Gorge Amphitheatre in George, Washington. It took place on Memorial Day weekend, running for three to four days.")
festival2 = Festival.create(name: "Bonaroo", location: "Tennessee", organizer_id: 2, image_url: "https://upload.wikimedia.org/wikipedia/en/2/2d/BonnarooDay.JPG", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"The Bonnaroo Music and Arts Festival is an American annual four-day music festival developed and produced by Superfly Presents and AC Entertainment. ... The festival features craftsmen and artisans selling unique products, food and drink vendors, comedy acts, silent disco, cinema experiences, and a Ferris wheel.")
festival3 = Festival.create(name: "Shambhala", location: "British Columbia", organizer_id: 3, image_url: "https://i0.wp.com/thissongissick.com/wp-content/uploads/2019/09/AMP-Don-Idio.jpg?w=750&ssl=1", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"Shambhala Music Festival is an annual electronic music festival held during last week in July at the Salmo River Ranch, a 500-acre (2.0 km2) farm, in the West Kootenay mountains near Nelson, British Columbia, Canada. The festival lasts 4 days and 3 nights and offers a mix of music and art in nature.")
festival4 = Festival.create(name: "Lollapalooza", location: "Chicago", organizer_id: 4, image_url: "https://www.chicagotribune.com/resizer/m8l2D8utZDIqCVUt2TJWqGbezFo=/800x533/top/arc-anglerfish-arc2-prod-tronc.s3.amazonaws.com/public/OGW7FSW2LBHAND6LPQWFK6QNKM.jpg", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"Lollapalooza, annual Chicago rock festival that features dozens of hip-hop, techno, and alternative rock performers over a four-day period. Lollapalooza was begun in 1991 by Jane's Addiction leader Perry Farrell as a multicity venue for his band's farewell tour.")
festival5 = Festival.create(name: "Coachella", location: "California", organizer_id: 1, image_url: "https://9b16f79ca967fd0708d1-2713572fef44aa49ec323e813b06d2d9.ssl.cf2.rackcdn.com/1140x_a10-7_cTC/Music-Coachella-Stagecoach-1591853035.jpg", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"The Coachella Valley Music and Arts Festival (commonly called Coachella or the Coachella Festival) is an annual music and arts festival held at the Empire Polo Club in Indio, California, in the Coachella Valley in the Colorado Desert.")
festival6 = Festival.create(name: "Austin City Limits", location: "Austin", organizer_id: 2, image_url: "https://coolmaterial.com/wp-content/uploads/2017/08/win-this-austin-city-limits-cm.jpg", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"The Austin City Limits (ACL) Music Festival is an annual music festival held in Zilker Park in Austin, Texas on two consecutive three-day weekends. Inspired by the KLRU/PBS music series of the same name, the festival is produced by Austin-based company C3 Presents, which also produces Lollapalooza.")
festival7 = Festival.create(name: "Electric Forrest", location: "Michigan", organizer_id: 3, image_url: "https://electricforestfestival.com/wp-content/uploads/2018/01/EFF2018_0622_021741-5429_JSL-copy-e1541723171754-1200x600.jpg", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"Electric Forest is a four-day, one-weekend, multi-genre event with a focus on electronic and jam band genres, held in Rothbury, Michigan, at the Double JJ Resort. In 2017 and 2018, the festival expanded to two weekends back to back, before switching back to one weekend for 2019.")
festival8 = Festival.create(name: "Bumbershoot", location: "Washington", organizer_id: 4, image_url: "https://www.seattleweekly.com/wp-content/uploads/2018/09/13398632_web1_BshootSaturday_TPain_11.jpg", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"Bumbershoot is an annual international music and arts festival held in Seattle, Washington. ... The name of the festival was taken from bumbershoot, a colloquial term for umbrella, probably coined in the 19th century as a portmanteau of the words umbrella and parachute.")
festival9 = Festival.create(name: "Voodoo", location: "New Orleans", organizer_id: 1, image_url: "https://bloximages.newyork1.vip.townnews.com/nola.com/content/tncms/assets/v3/editorial/b/3c/b3ca5582-c2a1-5223-bc0c-179f2f09fc8e/5d01197b1fbfc.image.jpg?resize=1200%2C837", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"The Voodoo Music + Arts Experience (formerly 'The Voodoo Music Experience'), commonly referred to as Voodoo or Voodoo Fest, is a multi-day music and arts festival held in City Park in New Orleans, Louisiana.")
festival10 = Festival.create(name: "Boston Calling", location: "Boston", organizer_id: 2, image_url: "https://2ab9pu2w8o9xpg6w26xnz04d-wpengine.netdna-ssl.com/wp-content/uploads/2019/11/boston-calling-live-2020.jpg", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"Boston Calling Music Festival is a three-day, multi-stage, outdoor festival featuring the biggest and best acts in live music, comedy, and visual arts. It is held at Harvard's Athletic Complex in Allston, MA on May 22, 23, & 24, 2020.")
festival11 = Festival.create(name: "Pitchfork Music Festival", location: "Chicago", organizer_id: 3, image_url: "https://d49r1np2lhhxv.cloudfront.net/www/admin/uploads/images/Top15FestivalsUSA_Pitchfork.jpg", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"Organised by independently focused music source Pitchfork Media, this three day event is a music genre melting pot of rock, hip-hop, electronic, jazz, punk and any other genre and sub-genre you want to celebrate. With a record fair, food, art and beverages from local and national vendors, this truly is a cultural feast.")
festival12 = Festival.create(name: "The Governors Ball", location: "New York", organizer_id: 4, image_url: "https://d49r1np2lhhxv.cloudfront.net/www/admin/uploads/images/Top15FestivalsUSA_GovBall.jpg", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"Another event which proves the music loving potential of Randall's Island Park is Govenors Ball, an exciting and infectious mix of rock, hip-hop, electronic, pop and folk. Providing a variety of music and food tastes, whether you look to kick back and relax or surrender yourself to beats and riffs, Governors Ball has what you want.")
festival13 = Festival.create(name: "Burning Man", location: "Nevada", organizer_id: 1, image_url: "https://media.resources.festicket.com/www/admin/uploads/images/BurningMan_iZei3tE.jpg", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"Burning Man is the ultimate festival, taking place in the Nevada desert. Started in 1986, the festival has grown into a cultural phenomenon and has inspired imitation festivals around the globe.")
festival14 = Festival.create(name: "Firefly Music Festival", location: "Delaware", organizer_id: 2, image_url: "https://media.resources.festicket.com/www/admin/uploads/images/Fireflypic.jpg", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"An American multi-genre behemoth, Firefly is the east coast's biggest camping festival. Everything about this festival is top of the line, from the lineup which is annually made up of the biggest names in popular music to an utterly immersive experience onsite with tons of areas to explore.")
festival15 = Festival.create(name: "Fyre", location: "Exuma", organizer_id: 2, image_url: "https://img.thedailybeast.com/image/upload/v1493448376/articles/2017/04/28/inside-ja-rule-s-fyre-festival-disaster-how-the-luxury-music-fest-became-lord-of-the-flies/170428-zimmerman-frye-tease_bqt3l0.jpg", start_date: DateTime.now + (rand * 365), duration: rand(5), description:"Fyre Festival was a fraudulent luxury music festival founded by Billy McFarland, CEO of Fyre Media Inc, and rapper Ja Rule. It was created with the intent of promoting the company's Fyre app for booking music talent.")

# favorite1 = Favorite.create(fan_id: Fan.all.sample.id, festival_id: Festival.all.sample.id, wishlist: true, comment: "no comment")
# favorite2 = Favorite.create(fan_id: Fan.all.sample.id, festival_id: Festival.all.sample.id, wishlist: true)
# favorite3 = Favorite.create(fan_id: Fan.all.sample.id, festival_id: Festival.all.sample.id, wishlist: true, comment: "Whatever")
# favorite4 = Favorite.create(fan_id: Fan.all.sample.id, festival_id: Festival.all.sample.id, wishlist: true, comment: "Love it")
# favorite5 = Favorite.create(fan_id: Fan.all.sample.id, festival_id: Festival.all.sample.id, wishlist: false, comment: "Meh")
# favorite6 = Favorite.create(fan_id: Fan.all.sample.id, festival_id: Festival.all.sample.id, wishlist: false)
# favorite7 = Favorite.create(fan_id: Fan.all.sample.id, festival_id: Festival.all.sample.id, wishlist: true, comment: "Whatever")
# favorite8 = Favorite.create(fan_id: Fan.all.sample.id, festival_id: Festival.all.sample.id, wishlist: false)
# favorite0 = Favorite.create(fan_id: Fan.all.sample.id, festival_id: Festival.all.sample.id, wishlist: false)

#ARTIST FESTIVAL
ar1 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar2 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar3 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar4 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar5 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar6 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar7 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar8 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar9 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar10 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar11 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar12= ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar13 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar14 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar15 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar16 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar17 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar18 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar19 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar20 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar21 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar22 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar23 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar24 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar25 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar26 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar27 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar28 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar29 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar30 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar31 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar32 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar33 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar34 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar35 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar36 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar37 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar38 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar39 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar40 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar41 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar42 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar43 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar44 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar45 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
ar46 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar47 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar48 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar49 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar50 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar51 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar52 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar53 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar54 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar55 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar56 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar57 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar58 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar59 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar60 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar61 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar62 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar63 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar64 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar65 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar66 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar67 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar68 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar69 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar70 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar71 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar72 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar73 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar74 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar75 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar76 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar77 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar78 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar79 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar80 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar81 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar82 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar83 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar84 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar85 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar86 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar87 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar88 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar89 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar90 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar91 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar92 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar93 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar94 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar95 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar96 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar97 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar98 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar99 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar100 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar101 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar102 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar103 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar104 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar105 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar106 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar107 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar108 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar109 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar110 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar111 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)
# ar112 = ArtistFestival.create(artist_id: Artist.all.sample.id, festival_id: Festival.all.sample.id)


puts 'seeds seeded!'
